version: "3.4"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    networks:
      - kafka_net
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    image: confluentinc/cp-kafka
    networks:
      - kafka_net
    ports:
      - "9091:9091" 
    environment:
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_DOCKER_INTERNAL://kafka:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_DOCKER_INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    restart: on-failure
  kafdrop:
    image: obsidiandynamics/kafdrop
    networks:
      - kafka_net
    ports:
      - "9000:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka:19091
    depends_on:
      - kafka
networks:
  kafka_net:
    driver: "bridge"